import type { PageCollectionItemBase, DataCollectionItemBase } from '@nuxt/content'

declare module '@nuxt/content' {
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface AboutCollectionItem extends PageCollectionItemBase {
    title: string;
    subtitle: string;
    description: string;
    image: string;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface EducationCollectionItem extends PageCollectionItemBase {
    title: string;
    subtitle: string;
    education: {
    institution: string;
    degree: string;
    period: string;
    description: string;
    skills: string[];
    }[];
    certifications: {
    title: string;
    issuer: string;
    date: string;
    icon: string;
    link: string;
    }[];
    skills: string[];
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface RepositoriesCollectionItem extends PageCollectionItemBase {
    title: string;
    subtitle: string;
    categories: string[];
    projects: {
    title: string;
    description: string;
    category: string;
    technologies: string[];
    image: string;
    demo?: string;
    github?: string;
    stars: number;
    language: string;
    }[];
    githubStats: {
    repos: number;
    stars: number;
    commits: number;
    followers: number;
    };
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ContactCollectionItem extends PageCollectionItemBase {
    title: string;
    subtitle: string;
    contactInfo: {
    email: string;
    phone: string;
    location: string;
    };
    socials: {
    name: string;
    url: string;
    icon: string;
    }[];
    availability: {
    status: string;
    note: string;
    };
    faqs: {
    question: string;
    answer: string;
    }[];
  }
  

  interface PageCollections {
    about: AboutCollectionItem
    education: EducationCollectionItem
    repositories: RepositoriesCollectionItem
    contact: ContactCollectionItem
  }

  interface Collections {
    about: AboutCollectionItem
    education: EducationCollectionItem
    repositories: RepositoriesCollectionItem
    contact: ContactCollectionItem
  }
}
